### ISSUE TITLE
Error when using Rspec Given w/ jruby (Ripper is not supported in jruby)

### ISSUE THREAD

**Issue by st23am** [jimweirich/rspec-given#11]
Using jruby 1.7.2 with rails 3.2.11 and rspec-given version 2.3.0

Running specs gives an error message: Ripper is not supported in jruby

**Comment by jimweirich** [comment]
Rats. Is there a Ripper replacement in JRuby?

**Comment by jimweirich** [comment]
I'll disable Sorcerer, Ripper (and hence Natural Assertions) when using JRuby for now.  If we can dig up a Ripper replacement, I'll consider adding it back in.

**Comment by st23am** [comment]
That sounds great. Thanks Jim! I'll be on the look out for something that could for now replace Ripper/Sorcerer. From this blog post http://www.jruby.org/2012/10/22/jruby-1-7-0.html it looks as though the jruby team is aware of the issue.

**Comment by PikachuEXE** [comment]
After updating to `2.3.1`, it seems that the gem is still trying to load `Sorcerer`
And that cause `LoadError` when trying to run any spec
even I specified `RSpec::Given.use_natural_assertions false` in `spec_helper.rb`

StackTrace:

```
from /usr/local/rvm/gems/ruby-1.9.3-p374/gems/rspec-given-2.3.1/lib/rspec/given/natural_assertion.rb:6:in `<top (required)>'
from /usr/local/rvm/gems/ruby-1.9.3-p374/gems/rspec-given-2.3.1/lib/rspec/given/extensions.rb:3:in `<top (required)>'
from /usr/local/rvm/gems/ruby-1.9.3-p374/gems/rspec-given-2.3.1/lib/rspec/given/core.rb:8:in `<top (required)>'
from /usr/local/rvm/gems/ruby-1.9.3-p374/gems/rspec-given-2.3.1/lib/rspec/given.rb:15:in `<top (required)>'
```

**Comment by jimweirich** [comment]
PikachuEXE ... What version of JRuby are you running?  (What's the value of JRUBY_VERSION?)

**Comment by PikachuEXE** [comment]
I am using MRI 1.9.3 p374, not JRuby

**Comment by jimweirich** [comment]
Hmm, I removed Sorcerer as a gem dependency for JRuby, but it is still getting loaded for non-JRuby platform.  Either gem install sorcerer or add to your Gemfile as appropriate.  I'll either add it back as a gem dependency or give a better error message in the next version.

Thanks for catching this.

**Comment by PikachuEXE** [comment]
`gem install` won't fix it
It has to be added into `Gemfile`
Maybe add an entry in Readme

**Comment by jimweirich** [comment]
I added the sorcerer dependency back into the gemspec.  It installs with JRuby, so that's ok.  But actually loading it is disabled in JRuby.  That should make everyone happy.

This change is is in rspec-given-2.3.2.

**Comment by PikachuEXE** [comment]
OK I am gonna try it :)

**Comment by PikachuEXE** [comment]
`2.3.2` does fix the problem. Thanks!

But I did not see `2.3.2` in repo @@?
