### ISSUE TITLE
documentation format removed when running under spork

### ISSUE THREAD

**Issue by timdiggins** [jimweirich/rspec-given#32]
When I run rspec with 'documentation' format, each `Then` outputs just 

```
    example at ./spec/features/user_pages_spec.rb:16
```

So, e.g.

```
$ rspec -f d spec/features/user_pages_spec.rb                                                                                                                                                         User pages
  As an admin
    with some users
      index
        example at ./spec/features/user_pages_spec.rb:16
    create user
      example at ./spec/features/user_pages_spec.rb
```

However, I'd really like them to use the source (like rspec does with `it { should.blah }` blocks

Does this sound possible? (I can see the problem with #31 so `And` might be ignored, or pulled together with preceding Thens).

**Comment by jimweirich** [comment]
When I run -fd agains the examples/stack/stack_spec.rb in the repo, I get:

```
$ rspec -fd examples/stack/stack_spec.rb 

Stack
  with an empty stack
    Then { stack.depth == 0 }
    when pushing
      Then { stack.depth == 1 }
      Then { stack.top == :an_item }
    when popping
      Then { result == Failure(Stack::UnderflowError, /empty/) }
  with one item
    when popping
      Then { pop_result == :an_item }
      Then { stack.depth == 0 }
  with several items
    when pushing
      Then { stack.top == :new_item }
      Then { stack.depth == original_depth + 1 }
    when popping
      Then { pop_result == :top_item }
      Then { stack.top == :second_item }
      Then { stack.depth == original_depth - 1 }

Finished in 0.01308 seconds
11 examples, 0 failures
```

This seems like reasonable output. Why are you getting different result?

**Comment by timdiggins** [comment]
Thanks for your response. That does look great, and after a bit of work, I've at least worked out why I'm getting a difference - I'm running my tests using [spork](https://github.com/sporkrb/spork) (rspec --drb). When I run the same tests (with same spec_helper) without connecting to the spork drb server, everything's fine. 

If I discover a fix I'll let you know. Haven't got a clue where to begin looking, and it doesn't feel very important (to me or rspec-given), now that there's an easy workaround for generating the documentation output.

**Comment by jimweirich** [comment]
There's no action on this, so I'm closing it.
