### ISSUE TITLE
Sorcerer error when an array is split over multiple lines

### ISSUE THREAD

**Issue by adamlogic** [jimweirich/rspec-given#36]
``` ruby
require 'rspec-given'

describe "arrays split over multiple lines" do
  When(:result) { 'anything' }
  Then { result == ['a',
                    'a'] }
end
```

Running this spec produces the following error:

``` bash
➔ rspec --color given_spec.rb
F

Failures:

  1) arrays split over multiple lines
     Failure/Error: Then { result == ['a',
     Sorcerer::Resource::NotSexpError:
       Not an S-EXPER: nil
     # ./given_spec.rb:5:in `block in Then'

Finished in 0.00046 seconds
1 example, 1 failure
```

Running ruby 2.0.0p195, rspec-given 3.4.0

**Comment by jimweirich** [comment]
RSpec/Given uses simple heuristics to determine the end of a Then clause. 

I've changed the code to actually parse the Then line and continue adding lines until we can get an entire parsable expression.  Version 3.5.0 (pushed and released) has those changes.

**Comment by jimweirich** [comment]
Thanks for finding this issue.

**Comment by adamlogic** [comment]
Thanks, Jim!
