### ISSUE TITLE
A more elegant way to check the message of an exception?

### ISSUE THREAD

**Issue by aviflax** [jimweirich/rspec-given#53]
I’m using given with MiniTest (and loving it) and this is the only way I’ve figured out to do this:

``` ruby
And do
  # This is awkward but it’s the only way I’ve figured out to capture
  # the exception and use it in an assertion.
  begin
    result.raise_please # will raise the original exception
  rescue RuntimeError => e
    e.message.include? 'not found'
  end
end
```

I’m new to Ruby though, so I figure I’m probably just missing something… thanks!

**Comment by docwhat** [comment]
The question is answered in the README.  Grep for `failure`.

Also, I think this repo is deprecated in favor of rspec-given/rspec-given

**Comment by aviflax** [comment]
@docwhat thanks. I didn’t see it there because the README doesn’t explicitly explain how to check the message with `have_failed`. And being new to Ruby, I didn’t recognize what was going on with `/empty/`. So, I’m good. Thank you!
