### ISSUE TITLE
Why do failures get captured?

### ISSUE THREAD

**Issue by Aryk** [jimweirich/rspec-given#55]
[This](https://github.com/jimweirich/rspec-given/blob/master/lib/given/failure.rb#L18) seems kind of strange.

So, basically, if I don't call a method on the object, then it quietly swallows errors. So for example, if I'm doing something like:

```ruby
When(:record) { create(:record) }
``` 

I have to make sure that *every* test uses it. What if one test wants to access the record, but another one just wants to do Record.count == 1? Then you wouldn't know why it isn't working since Record.count does not actually call `record` directly.

**Comment by mikegee** [comment]
Hi @Aryk, maintenance and discussion of this project has moved to https://github.com/rspec-given/rspec-given since Jim is no longer with us.

**Comment by Aryk** [comment]
thanks @mikegee
