### ISSUE TITLE
Several Then-s in the same context with And-s

### ISSUE THREAD

**Issue by VorontsovIE** [jimweirich/rspec-given#7]
What if several Then-And blocks are used in the same context?
Imagine very long-creating stack object. In such a case I'd write some sequece of change-test-change-test in a way like this (not very elegant, but this helps avoiding recreating my object)
...
  Then { stack.depth.should == 1 }
  And { stack.push(:smth)
         stack.depth.should == 2 }

It works well, but if I repeat this two clauses
...  
  Then { stack.depth.should == 1 }
  And { stack.push(:smth)
         stack.depth.should == 2 }
  Then { stack.depth.should == 1 }
  And { stack.push(:smth)
         stack.depth.should == 2 } # error here!

, I'll get an error because And-s are common for all Then-s in a context. so the last And's stack.depth == 3, not 2
One should either make And-s be bounded to the latter Then clause or to include a fix to documentation that make such behavior of And clear to a newcomer.

---

Also not to make another issue, documentation can be made a bit more precise if one correct 
"There should only be one When clause for a given context." 
with 
"There should be not more than one When clause for a given context."
An example of this even illustrated in a Stack example:
   Given(:initial_contents) { [] }
   Then { stack.depth.should == 0 }

**Comment by jimweirich** [comment]
On Sep 21, 2012, at 1:57 PM, Ilya Vorontsov notifications@github.com wrote:

> What if several Then-And blocks are used in the same context?
> Imagine very long-creating stack object. In such a case I'd write some sequece of change-test-change-test in a way like this (not very elegant, but this helps avoiding recreating my object)
> ...
> Then { stack.depth.should == 1 }
> And { stack.push(:smth)
> stack.depth.should == 2 }
> 
> It works well, but if I repeat this two clauses
> ...
> 
> Then { stack.depth.should == 1 }
> And { stack.push(:smth)
> stack.depth.should == 2 }
> Then { stack.depth.should == 1 }
> And { stack.push(:smth)
> stack.depth.should == 2 } # error here!
> 
> , I'll get an error because And-s are common for all Then-s in a context. so the last And's stack.depth == 3, not 2
> One should either make And-s be bounded to the latter Then clause or to include a fix to documentation that make such behavior of And clear to a newcomer.

Then's (and And's in turn) should not have state changing behavior, ever.

I'll review the docs to make sure that is clear.

> Also not to make another issue, documentation can be made a bit more precise if one correct 
> "There should only be one When clause for a given context." 
> with 
> "There should be not more than one When clause for a given context."
> An example of this even illustrated in a Stack example:
> Given(:initial_contents) { [] }
> Then { stack.depth.should == 0 }

Thanks.

## 

-- Jim Weirich
-- jim.weirich@gmail.com

**Comment by jimweirich** [comment]
I emphasized the idempotent nature of the Then/And clauses in the Readme, and made the suggested wording change w.r.t. 1 when clause per context.

Thanks.
